trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"

  - script: npm install -g expo-cli eas-cli
    displayName: "Install Expo & EAS"

  - script: npm install
    displayName: "Install dependencies"

  - script: npx expo-doctor
    displayName: "Expo doctor"

  - script: npm run lint
    displayName: "ESLint - Code Quality Check"
    continueOnError: false

  - script: npm run format:check
    displayName: "Prettier - Code Formatting Check"
    continueOnError: false

  - script: npm run type-check
    displayName: "TypeScript - Type Checking"
    continueOnError: false

  - script: npm run test:ci
    displayName: "Jest - Run Tests & Coverage"
    continueOnError: false

  - script: |
      eas build --platform all --profile production --non-interactive
    displayName: "EAS Build (Android + iOS)"
    env:
      EXPO_TOKEN: $(EXPO_TOKEN)

  - script: |
      eas submit --platform all --profile production --non-interactive
    displayName: "EAS Submit (Play Store + App Store)"
    env:
      EXPO_TOKEN: $(EXPO_TOKEN)
